name: Code Scanning

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code-scanning:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: CodeQL Analysis
        uses: github/codeql-action@v2
        with:
          # Set the repository's token, provided by GitHub Actions
          # Required for the CodeQL runner to upload results
          token: ${{ secrets.GITHUB_TOKEN }}

      # Add additional steps for other analysis tools if desired
